/**
 * /timer/[id] — Shareable live draw timer page
 *
 * Designed to be linked from a pinned X post. The OG image is dynamically
 * generated by /api/og?id=[id] so the X card preview shows current draw
 * state. The page itself counts down in real time via TimerClient.
 */

import { Metadata } from 'next';
import TimerClient from './TimerClient';

type Props = { params: Promise<{ id: string }> };

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { id } = await params;
  const base = 'https://rando-mu.vercel.app';
  const ogImage = `${base}/api/og?id=${id}`;

  return {
    title: '$RANDO — Live Draw Timer',
    description:
      'Live countdown to the next $RANDO prize draw on Solana. Hold ≥0.25% of supply without selling to qualify. One random winner every draw.',
    openGraph: {
      title: '$RANDO — Live Draw Timer',
      description: 'Live countdown and prize pool for the next $RANDO draw.',
      url: `${base}/timer/${id}`,
      siteName: 'Rando',
      images: [{ url: ogImage, width: 1200, height: 630, alt: '$RANDO Draw Timer' }],
      type: 'website',
    },
    twitter: {
      card: 'summary_large_image',
      title: '$RANDO — Live Draw Timer',
      description: 'Live countdown and prize pool for the next $RANDO draw.',
      images: [ogImage],
    },
  };
}

export default async function TimerPage({ params }: Props) {
  const { id } = await params;
  return <TimerClient projectId={id} />;
}
